// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.miguelo.examplelogin.repository;

import com.miguelo.examplelogin.repository.ProductoRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductoRepository_Roo_Jpa_Repository {
    
    declare @type: ProductoRepository: @Transactional(readOnly = true);
    
}
